services:

#  DB postgres
  postgres:
    image: postgres:16-alpine
    container_name: analytics-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

#  local inference-runtime for LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  pgdata:
  ollama:

#docker exec -it ollama ollama pull {model}
#docker exec -it ollama ollama rm {model}

# models:
# qwen3:4b
# qwen2.5-coder:7b
# qwen2.5-coder:3b
# phi3:mini
# stablelm:3b
# deepseek-coder:6.7b


